services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ProyectateIA2025
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - ./mongo:/data/db